### ISSUE TITLE
Error.yml does not exist

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#3]
Shouldn't we have a fallback for this?

```
Uncaught Exception: The file does not exist: …/starterkit/site/blueprints/error.yml in …/starterkit/kirby/vendor/getkirby/filesystem/src/FileSystem/File.php:364
Stack trace:
#0 …/starterkit/kirby/vendor/getkirby/data/src/Data/Data.php(121): Kirby\FileSystem\File->read()
#1 …/starterkit/kirby/src/Cms/Blueprint.php(49): Kirby\Data\Data::read(Object(Kirby\FileSystem\File))
#2 …/starterkit/kirby/api/types/page/content.php(9): Kirby\Cms\Blueprint->toArray()
#3 [internal function]: Kirby\Api\Api->{closure}(Object(Kirby\Cms\Page))
#4 …/starterkit/kirby/src/Api/Api.php(93): Closure->call(Object(Kirby\Api\Api), Object(Kirby\Cms\Page))
#5 …/starterkit/kirby/api/types/page.php(12): Kirby\Api\Api->output('page/content', Object(Kirby\Cms\Page))
#6 [internal function]: Kirby\Api\Api->{clos in …/starterkit/kirby/vendor/getkirby/filesystem/src/FileSystem/File.php on line 364
```

**Comment by bastianallgeier** [comment]
Shit! I already fixed that for the demo. But forgot to take it over into master

**Comment by bastianallgeier** [comment]
This is now fixed
