### ISSUE TITLE
[3.6.3-rc.1] New url overwrite config doesn't overwrite panel URL

### ISSUE THREAD

**Issue by samzzi** [k-next/kirby#4185]
## Description
When you use the url overwrite option in the config the panel url doesn't get overwritten which stops the panel from working.
Example: https://smooth-meadow-s8t0nkgaql.ploi.link/panel/login

You'll notice in the rendered HTML the `$url` is wrong (although the `$urls` are correct:

```html
const json = { 
... 
"$urls":{"api":"https:\/\/smooth-meadow-s8t0nkgaql.ploi.link\/api","site":"https:\/\/smooth-meadow-s8t0nkgaql.ploi.link\/"},"
 ... 
,"$url":"http:\/\/kirbytest.previewsite.be\/panel\/login", 
...
}};
```

The config setting I used:

```php
return [
    'debug' => true,
    'panel' => ['install' => true],
     'url' => 'https://smooth-meadow-s8t0nkgaql.ploi.link/',
];
```

**Expected behavior**  
The panel to be working? 😊

## To reproduce

1. Use a website setup with multiple URL's where
2. Add the 'url' overwrite in the config to enable the correct url for your site

## Your setup
**Kirby Version**  : 3.6.3-rc.1

**Console output**  

```js
Uncaught SyntaxError: Unexpected token ':'
index.js:1 DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http://kirbytest.previewsite.be/panel/login' cannot be created in a document with origin 'https://smooth-meadow-s8t0nkgaql.ploi.link' and URL 'https://smooth-meadow-s8t0nkgaql.ploi.link/panel/login'.
    at Object.onPushState (https://smooth-meadow-s8t0nkgaql.ploi.link/media/panel/911cd65cb7f3f66bc0f75ce7852776e0/js/index.js:1:7778)
    at pt.setState (https://smooth-meadow-s8t0nkgaql.ploi.link/media/panel/911cd65cb7f3f66bc0f75ce7852776e0/js/index.js:1:18165)
    at pt.init (https://smooth-meadow-s8t0nkgaql.ploi.link/media/panel/911cd65cb7f3f66bc0f75ce7852776e0/js/index.js:1:16374)
    at a.created (https://smooth-meadow-s8t0nkgaql.ploi.link/media/panel/911cd65cb7f3f66bc0f75ce7852776e0/js/index.js:1:7473)
    at Vt (https://smooth-meadow-s8t0nkgaql.ploi.link/media/panel/911cd65cb7f3f66bc0f75ce7852776e0/js/vendor.js:6:11291)
    at nn (https://smooth-meadow-s8t0nkgaql.ploi.link/media/panel/911cd65cb7f3f66bc0f75ce7852776e0/js/vendor.js:6:25303)
    at a.Cn._init (https://smooth-meadow-s8t0nkgaql.ploi.link/media/panel/911cd65cb7f3f66bc0f75ce7852776e0/js/vendor.js:6:32894)
    at new a (https://smooth-meadow-s8t0nkgaql.ploi.link/media/panel/911cd65cb7f3f66bc0f75ce7852776e0/js/vendor.js:6:30461)
    at https://smooth-meadow-s8t0nkgaql.ploi.link/media/panel/911cd65cb7f3f66bc0f75ce7852776e0/js/vendor.js:6:19454
    at init (https://smooth-meadow-s8t0nkgaql.ploi.link/media/panel/911cd65cb7f3f66bc0f75ce7852776e0/js/vendor.js:6:19485)
```

**Comment by afbora** [comment]
Because when `HTTP_X_FORWARDED_HOST` returns empty, it takes `SERVER_NAME` data before `HTTP_HOST`.

Maybe we should read all the header data and compare it with the allowed hosts list. Something like that:

````php
public static function host(bool $forwarded = false): string
{
    $host = null;
    $hosts = [];

    // insecure host parameters are only allowed when hosts
    // are validated against set of host patterns
    $allowInsecure = empty(static::$hosts) === false;

    if ($allowInsecure === true && static::isBehindProxy() === true) {
        $hosts[] = static::get('HTTP_X_FORWARDED_HOST');
    }

    $hosts[] = static::get('SERVER_NAME');

    if ($allowInsecure === true) {
        $hosts[] = static::get('HTTP_HOST');
    }

    $hosts[] = static::get('SERVER_ADDR');

    // remove empty hosts
    $hosts = array_filter($hosts);

    foreach ($hosts as $host) {
        if (static::isAllowedHost($host) === true) {
            return explode(':', $host)[0];
        }
    }
    
    return '';
}
````

**Comment by lukasbestle** [comment]
@afbora I think this approach makes sense. It could even be shortened to:

```php
$hosts[] = static::get('SERVER_NAME');
$hosts[] = static::get('SERVER_ADDR');

// insecure host parameters are only allowed when hosts
// are validated against set of host patterns
if (empty(static::$hosts) === false) {
    $hosts[] = static::get('HTTP_HOST');
    $hosts[] = static::get('HTTP_X_FORWARDED_HOST');
}
```

But we need to be careful about what I wrote on Discord.

**Comment by bastianallgeier** [comment]
✅
