### ISSUE TITLE
[v4] Uploading a file via drag and drop into the textarea is broken

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5331]
## Description
When dropping a file from my system into the textarea the upload dialog shows up. When I press the button to save the file the upload progresses and the dialog window disappears. The kirbytag doesn't get added to the textarea though and the file doesn't appear in the files section. When I reload the panel the file appears in the files section.

## Your setup
**Kirby Version**  
4.0.0-alpha.3

**Console output**  
index.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at a.insertUpload (index.js:1:174245)
    at Object.emit (index.js:1:354127)
    at Object.done (index.js:1:364504)
    at Object.success (index.js:1:366801)
    at XMLHttpRequest.<anonymous> (index.js:1:341227)

**Your system (please complete the following information)**
Chrome 114.0.5735.198

**Comment by mrflix** [comment]
🔥
