### ISSUE TITLE
[V4] Issue with form submission in Uniform

### ISSUE THREAD

**Issue by MikeHarrison** [k-next/kirby#5618]
## Description
When submitting a form, I am getting an error in the PHP log and the form is failing to submit

**Expected behavior**  
A successful form submission. This setup was working in the latest stable v3 version of Kirby

## To reproduce

1. Set up Kirby V4, and add the Uniform plugin
2. Create a simple form, use Uniform to handle the submission

## Your setup
**Kirby Version**  
Kirby 4 Beta 1

**PHP Error Log**
```
[11-Sep-2023 21:19:50 UTC] TypeError: Kirby\Toolkit\Str::template(): Argument #3 ($options) must be of type array, string given, called in /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Actions/EmailAction.php on line 124 and defined in /Users/mike/Dropbox/boilerplate/kirby/src/Toolkit/Str.php:1244
Stack trace:
#0 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Actions/EmailAction.php(124): Kirby\Toolkit\Str::template('New form submis...', Array, '')
#1 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Actions/EmailAction.php(134): Uniform\Actions\EmailAction->resolveTemplate('New form submis...')
#2 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Actions/EmailAction.php(38): Uniform\Actions\EmailAction->getSubject()
#3 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Form.php(284): Uniform\Actions\EmailAction->perform()
#4 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Form.php(207): Uniform\Form->perform(Object(Uniform\Actions\EmailAction))
#5 /Users/mike/Dropbox/boilerplate/site/plugins/kirby-uniform/src/Form.php(253): Uniform\Form->action(Object(Uniform\Actions\EmailAction), Array)
#6 /Users/mike/Dropbox/boilerplate/site/controllers/default.php(80): Uniform\Form->__call('emailAction', Array)
#7 [internal function]: Kirby\Cms\App->{closure}(Object(Kirby\Cms\App), Object(Kirby\Cms\Page), Object(Kirby\Cms\Site))
#8 /Users/mike/Dropbox/boilerplate/kirby/src/Toolkit/Controller.php(58): Closure->call(Object(Kirby\Cms\App), kirby: Object(Kirby\Cms\App), page: Object(Kirby\Cms\Page), site: Object(Kirby\Cms\Site))
#9 /Users/mike/Dropbox/boilerplate/kirby/src/Cms/App.php(450): Kirby\Toolkit\Controller->call(Object(Kirby\Cms\App), Array)
#10 /Users/mike/Dropbox/boilerplate/kirby/src/Cms/Page.php(316): Kirby\Cms\App->controller('default', Array, 'html')
#11 /Users/mike/Dropbox/boilerplate/kirby/src/Cms/Page.php(996): Kirby\Cms\Page->controller(Array, 'html')
#12 /Users/mike/Dropbox/boilerplate/kirby/src/Cms/App.php(776): Kirby\Cms\Page->render()
#13 /Users/mike/Dropbox/boilerplate/kirby/src/Cms/App.php(1190): Kirby\Cms\App->io(Object(Kirby\Cms\Page))
#14 /Users/mike/Dropbox/Boilerplate/index.php(5): Kirby\Cms\App->render()  
```

**Comment by afbora** [comment]
Issue is moved to the related plugin repository https://github.com/mzur/kirby-uniform/issues/250
