### ISSUE TITLE
[v4] Incomplete return type of Kirby\Cms\Page::modified()

### ISSUE THREAD

**Issue by elyukai** [k-next/kirby#5625]
## Description

The return type is `string|int`, but it may return `null` in line 835, which causes an exception.

https://github.com/getkirby/kirby/blob/bc43ab0bc3cf3bebe7ad0116b484ca5470210260/src/Cms/Page.php#L822-L839

**Expected behavior**  
The return type should be `string|int|null` or no `null` value should be returned.

**Screenshots**  
n/a

## To reproduce

1. Create a virtual page in the router
2. Navigate to the route
3. See error

## Your setup
**Kirby Version**  
4.0.0-beta.1

**Console output**
```
[Wed Sep 13 18:38:51 2023] TypeError: Kirby\Cms\Page::modified(): Return value must be of type string|int, null returned in <workspace>/kirby/src/Cms/Page.php:835
Stack trace:
#0 <workspace>/site/plugins/kirby-seo/snippets/head.php(18): Kirby\Cms\Page->modified('yyyy-MM-dd')
#1 <workspace>/kirby/src/Filesystem/F.php(425): include('<workspace>...')
#2 <workspace>/kirby/src/Filesystem/F.php(364): Kirby\Filesystem\F::loadIsolated('<workspace>...', Array)
#3 <workspace>/kirby/src/Filesystem/F.php(372): Kirby\Filesystem\F::Kirby\Filesystem\{closure}()
#4 <workspace>/kirby/src/Toolkit/Tpl.php(36): Kirby\Filesystem\F::load('<workspace>...', NULL, Array)
#5 <workspace>/kirby/src/Template/Snippet.php(172): Kirby\Toolkit\Tpl::load('<workspace>...', Array)
#6 <workspace>/kirby/config/components.php(301): Kirby\Template\Snippet::factory('seo/head', Array, false)
#7 <workspace>/kirby/src/Cms/App.php(1552): Kirby\Cms\Core->{closure}(Object(Kirby\Cms\App), 'seo/head', Array, false)
#8 <workspace>/kirby/config/helpers.php(517): Kirby\Cms\App->snippet('seo/head', Array, false, false)
#9 <workspace>/site/snippets/layout.php(8): snippet('seo/head')
#10 <workspace>/kirby/src/Filesystem/F.php(425): include('<workspace>...')
#11 <workspace>/kirby/src/Filesystem/F.php(364): Kirby\Filesystem\F::loadIsolated('<workspace>...', Array)
#12 <workspace>/kirby/src/Filesystem/F.php(372): Kirby\Filesystem\F::Kirby\Filesystem\{closure}()
#13 <workspace>/kirby/src/Toolkit/Tpl.php(36): Kirby\Filesystem\F::load('<workspace>...', NULL, Array)
#14 <workspace>/kirby/src/Template/Snippet.php(248): Kirby\Toolkit\Tpl::load('<workspace>...', Array)
#15 <workspace>/kirby/src/Template/Template.php(183): Kirby\Template\Snippet->render(Array, Array)
#16 <workspace>/kirby/src/Cms/Page.php(1006): Kirby\Template\Template->render(Array)
#17 <workspace>/kirby/src/Cms/App.php(776): Kirby\Cms\Page->render()
#18 <workspace>/kirby/src/Cms/App.php(1190): Kirby\Cms\App->io(Object(Kirby\Cms\Page))
#19 <workspace>/index.php(5): Kirby\Cms\App->render()
#20 <workspace>/kirby/router.php(14): require('<workspace>...')
#21 {main}
```

**Your system (please complete the following information)**
 - Device: MacBook Pro Late 2021
 - OS: macOS 13.5.2
 - Browser: Safari
 - Version: 16.6

**Additional context**  
n/a

**Comment by afbora** [comment]
Thanks for the report. The issue is duplicated of https://github.com/getkirby/kirby/issues/5591 and already fixed in 4.0.0-beta.2

**Comment by elyukai** [comment]
Oh, I'm sorry, I searched for a duplicate but I must have overlooked that. My bad. 😬

**Comment by lukasbestle** [comment]
@elyukai Don't worry, thanks for reporting it :)
