### ISSUE TITLE
Panel not opened after login when page doesn’t exist

### ISSUE THREAD

**Issue by linusrogge** [k-next/kirby#6682]
## Description
This might be a bit of an edge case, but when logging in to the Panel using a route that points to a specific page (eg. `http://localhost:8000/panel/pages/example`) which **doesn’t** exist in the current installation (but was suggested by the browser from another project for example), it will show a modal saying this page doesn’t exist but will **stay on the login screen**. 

A simple reload or signing in again will do, but it’s just an extra step that can be spared.

<img width="638" alt="Screenshot 2024-09-17 at 4 22 10 PM" src="https://github.com/user-attachments/assets/4003ad04-c57f-46f9-ade0-d9e0323dc6d0">

**Expected behavior**  

Kirby should redirect either to the Panel’s “Page not found” page or simply to `/panel/site`.

## To reproduce

1. Start a local development server and navigate to a non-existent Panel route (eg. `/panel/pages/idontexist`)
2. Kirby redirects to login: enter your credentials
3. Hit enter/click “Sign in”
4. Modal should appear

## Your setup
**Kirby Version**  
v4.4.0

**Console output**  
``` 
GET http://localhost:8000/panel/pages/schule+digitalisierung+luinet-einfuehrung 404 (Not Found)
gu @ index.min.js:2
request @ index.min.js:2
get @ index.min.js:2
open @ index.min.js:2
load @ index.min.js:2
open @ index.min.js:2
reload @ index.min.js:2
login @ index.min.js:2
await in login
submit @ index.min.js:2
_n @ vue.min.js:11
r @ vue.min.js:11
i._wrapper @ vue.min.js:11
index.min.js:2 pu: The request to http://localhost:8000/panel/pages/schule+digitalisierung+luinet-einfuehrung failed
    at ku (http://localhost:8000/media/panel/9b4bffa460105781f82b1d463bde8200/js/index.min.js:2:380455)
    at async gu (http://localhost:8000/media/panel/9b4bffa460105781f82b1d463bde8200/js/index.min.js:2:380038)
    at async Object.get (http://localhost:8000/media/panel/9b4bffa460105781f82b1d463bde8200/js/index.min.js:2:403857)
    at async Object.open (http://localhost:8000/media/panel/9b4bffa460105781f82b1d463bde8200/js/index.min.js:2:404014)
    at async Object.load (http://localhost:8000/media/panel/9b4bffa460105781f82b1d463bde8200/js/index.min.js:2:384911)
```

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: MacOS 15.0
 - Browser: Any (Tested in Chrome, Safari)

**Comment by bastianallgeier** [comment]
I think this issue existed before 4.4.0, right? I just want to make sure that we don't mark it as a regression.

**Comment by afbora** [comment]
Yes, there was.
